// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EndpointRequest struct {
	Endpoint             *Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EndpointRequest) Reset()         { *m = EndpointRequest{} }
func (m *EndpointRequest) String() string { return proto.CompactTextString(m) }
func (*EndpointRequest) ProtoMessage()    {}
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *EndpointRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointRequest.Unmarshal(m, b)
}
func (m *EndpointRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointRequest.Marshal(b, m, deterministic)
}
func (m *EndpointRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointRequest.Merge(m, src)
}
func (m *EndpointRequest) XXX_Size() int {
	return xxx_messageInfo_EndpointRequest.Size(m)
}
func (m *EndpointRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointRequest proto.InternalMessageInfo

func (m *EndpointRequest) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type EndpointResponse struct {
	Endpoint             *Endpoint `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EndpointResponse) Reset()         { *m = EndpointResponse{} }
func (m *EndpointResponse) String() string { return proto.CompactTextString(m) }
func (*EndpointResponse) ProtoMessage()    {}
func (*EndpointResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *EndpointResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndpointResponse.Unmarshal(m, b)
}
func (m *EndpointResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndpointResponse.Marshal(b, m, deterministic)
}
func (m *EndpointResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndpointResponse.Merge(m, src)
}
func (m *EndpointResponse) XXX_Size() int {
	return xxx_messageInfo_EndpointResponse.Size(m)
}
func (m *EndpointResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndpointResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndpointResponse proto.InternalMessageInfo

func (m *EndpointResponse) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type Endpoint struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Proto                string   `protobuf:"bytes,2,opt,name=proto,proto3" json:"proto,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Endpoint) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Endpoint) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RouteRequest struct {
	Route                *Route    `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Endpoint             *Endpoint `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RouteRequest) Reset()         { *m = RouteRequest{} }
func (m *RouteRequest) String() string { return proto.CompactTextString(m) }
func (*RouteRequest) ProtoMessage()    {}
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *RouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteRequest.Unmarshal(m, b)
}
func (m *RouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteRequest.Marshal(b, m, deterministic)
}
func (m *RouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteRequest.Merge(m, src)
}
func (m *RouteRequest) XXX_Size() int {
	return xxx_messageInfo_RouteRequest.Size(m)
}
func (m *RouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteRequest proto.InternalMessageInfo

func (m *RouteRequest) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *RouteRequest) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type RouteResponse struct {
	Route                *Route    `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Endpoint             *Endpoint `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RouteResponse) Reset()         { *m = RouteResponse{} }
func (m *RouteResponse) String() string { return proto.CompactTextString(m) }
func (*RouteResponse) ProtoMessage()    {}
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *RouteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteResponse.Unmarshal(m, b)
}
func (m *RouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteResponse.Marshal(b, m, deterministic)
}
func (m *RouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteResponse.Merge(m, src)
}
func (m *RouteResponse) XXX_Size() int {
	return xxx_messageInfo_RouteResponse.Size(m)
}
func (m *RouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteResponse proto.InternalMessageInfo

func (m *RouteResponse) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *RouteResponse) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type Route struct {
	Route                string   `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Cost                 int64    `protobuf:"varint,3,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Route) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Route) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type MetricsRequest struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsRequest) Reset()         { *m = MetricsRequest{} }
func (m *MetricsRequest) String() string { return proto.CompactTextString(m) }
func (*MetricsRequest) ProtoMessage()    {}
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *MetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsRequest.Unmarshal(m, b)
}
func (m *MetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsRequest.Marshal(b, m, deterministic)
}
func (m *MetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsRequest.Merge(m, src)
}
func (m *MetricsRequest) XXX_Size() int {
	return xxx_messageInfo_MetricsRequest.Size(m)
}
func (m *MetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsRequest proto.InternalMessageInfo

func (m *MetricsRequest) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type MetricsResponse struct {
	Port                 string   `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetricsResponse) Reset()         { *m = MetricsResponse{} }
func (m *MetricsResponse) String() string { return proto.CompactTextString(m) }
func (*MetricsResponse) ProtoMessage()    {}
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *MetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsResponse.Unmarshal(m, b)
}
func (m *MetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsResponse.Marshal(b, m, deterministic)
}
func (m *MetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsResponse.Merge(m, src)
}
func (m *MetricsResponse) XXX_Size() int {
	return xxx_messageInfo_MetricsResponse.Size(m)
}
func (m *MetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsResponse proto.InternalMessageInfo

func (m *MetricsResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func init() {
	proto.RegisterType((*EndpointRequest)(nil), "api.EndpointRequest")
	proto.RegisterType((*EndpointResponse)(nil), "api.EndpointResponse")
	proto.RegisterType((*Endpoint)(nil), "api.Endpoint")
	proto.RegisterType((*RouteRequest)(nil), "api.RouteRequest")
	proto.RegisterType((*RouteResponse)(nil), "api.RouteResponse")
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*MetricsRequest)(nil), "api.MetricsRequest")
	proto.RegisterType((*MetricsResponse)(nil), "api.MetricsResponse")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x14, 0xfc, 0x6d, 0xfb, 0x6b, 0x69, 0x9f, 0x8d, 0x2d, 0x6b, 0x95, 0xd0, 0x53, 0x09, 0x0a, 0xf5,
	0x52, 0xa5, 0x5e, 0xeb, 0x41, 0xa8, 0xa0, 0xa0, 0x97, 0xf4, 0xa8, 0x97, 0xb8, 0x3e, 0x70, 0x0f,
	0x66, 0xd7, 0xdd, 0x4d, 0xc1, 0x8f, 0xea, 0xb7, 0x91, 0xfd, 0x97, 0x1a, 0x11, 0x41, 0xf1, 0xf6,
	0xde, 0xcb, 0xcc, 0xec, 0xcc, 0x10, 0x48, 0x0a, 0xc9, 0x4f, 0x0a, 0xc9, 0xe7, 0x52, 0x09, 0x23,
	0x68, 0xbb, 0x90, 0x3c, 0x5b, 0xc2, 0xf0, 0xb2, 0x7c, 0x94, 0x82, 0x97, 0x26, 0xc7, 0x97, 0x0a,
	0xb5, 0xa1, 0xc7, 0xd0, 0xc3, 0x70, 0x4a, 0xc9, 0x94, 0xcc, 0x76, 0x16, 0xc9, 0xdc, 0xb2, 0x6a,
	0x5c, 0xfd, 0x39, 0x3b, 0x87, 0xd1, 0x96, 0xad, 0xa5, 0x28, 0x35, 0xfe, 0x84, 0x7e, 0x05, 0xbd,
	0x78, 0xa5, 0x14, 0xfe, 0x3f, 0x09, 0xed, 0x29, 0xfd, 0xdc, 0xcd, 0x74, 0x0c, 0x1d, 0x67, 0x35,
	0x6d, 0xb9, 0xa3, 0x5f, 0x2c, 0x52, 0x0a, 0x65, 0xd2, 0xb6, 0x47, 0xda, 0x39, 0xbb, 0x83, 0x41,
	0x2e, 0x2a, 0x83, 0x31, 0xc3, 0x14, 0x3a, 0xca, 0xee, 0xc1, 0x01, 0x38, 0x07, 0x1e, 0xe1, 0x3f,
	0x34, 0x6c, 0xb6, 0xbe, 0xb7, 0x79, 0x0f, 0x49, 0x10, 0x0f, 0x11, 0xff, 0x54, 0xfd, 0x1a, 0x3a,
	0x8e, 0x6a, 0xd3, 0x6e, 0x55, 0xfb, 0x51, 0xe9, 0x00, 0xba, 0x5a, 0x54, 0x8a, 0x61, 0x28, 0x21,
	0x6c, 0xb6, 0x05, 0x66, 0xfb, 0xb2, 0x2d, 0xb4, 0x73, 0x37, 0x67, 0x87, 0xb0, 0x7b, 0x8b, 0x46,
	0x71, 0xa6, 0x63, 0x0f, 0xb1, 0x2b, 0xf2, 0xa1, 0xab, 0x23, 0x18, 0xd6, 0xa8, 0x10, 0xe8, 0x0b,
	0xd8, 0xe2, 0x8d, 0xc0, 0x68, 0xc5, 0x35, 0x13, 0x1b, 0x54, 0xaf, 0x6b, 0x54, 0x1b, 0xce, 0x90,
	0xae, 0x60, 0xb8, 0x36, 0x0a, 0x8b, 0xe7, 0x18, 0x44, 0xd3, 0x71, 0x33, 0x98, 0x7f, 0x78, 0xb2,
	0xff, 0xe9, 0xea, 0x1f, 0xca, 0xfe, 0xcd, 0xc8, 0x29, 0xa1, 0x17, 0x30, 0xf0, 0x2a, 0x2e, 0xf8,
	0xaf, 0x24, 0x96, 0x90, 0xdc, 0x08, 0x56, 0x18, 0x0c, 0x51, 0xe8, 0x9e, 0x43, 0x37, 0xe3, 0x4f,
	0xc6, 0xcd, 0x63, 0x54, 0x78, 0xe8, 0xba, 0x3f, 0xe9, 0xec, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x39,
	0x5b, 0xad, 0x32, 0x12, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoveryServiceClient interface {
	StreamEndpoints(ctx context.Context, opts ...grpc.CallOption) (DiscoveryService_StreamEndpointsClient, error)
	StreamRoutes(ctx context.Context, opts ...grpc.CallOption) (DiscoveryService_StreamRoutesClient, error)
	LocateMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
}

type discoveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryServiceClient(cc *grpc.ClientConn) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) StreamEndpoints(ctx context.Context, opts ...grpc.CallOption) (DiscoveryService_StreamEndpointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DiscoveryService_serviceDesc.Streams[0], "/api.DiscoveryService/StreamEndpoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryServiceStreamEndpointsClient{stream}
	return x, nil
}

type DiscoveryService_StreamEndpointsClient interface {
	Send(*EndpointRequest) error
	Recv() (*EndpointResponse, error)
	grpc.ClientStream
}

type discoveryServiceStreamEndpointsClient struct {
	grpc.ClientStream
}

func (x *discoveryServiceStreamEndpointsClient) Send(m *EndpointRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *discoveryServiceStreamEndpointsClient) Recv() (*EndpointResponse, error) {
	m := new(EndpointResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *discoveryServiceClient) StreamRoutes(ctx context.Context, opts ...grpc.CallOption) (DiscoveryService_StreamRoutesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DiscoveryService_serviceDesc.Streams[1], "/api.DiscoveryService/StreamRoutes", opts...)
	if err != nil {
		return nil, err
	}
	x := &discoveryServiceStreamRoutesClient{stream}
	return x, nil
}

type DiscoveryService_StreamRoutesClient interface {
	Send(*EndpointRequest) error
	Recv() (*EndpointResponse, error)
	grpc.ClientStream
}

type discoveryServiceStreamRoutesClient struct {
	grpc.ClientStream
}

func (x *discoveryServiceStreamRoutesClient) Send(m *EndpointRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *discoveryServiceStreamRoutesClient) Recv() (*EndpointResponse, error) {
	m := new(EndpointResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *discoveryServiceClient) LocateMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/api.DiscoveryService/LocateMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServiceServer is the server API for DiscoveryService service.
type DiscoveryServiceServer interface {
	StreamEndpoints(DiscoveryService_StreamEndpointsServer) error
	StreamRoutes(DiscoveryService_StreamRoutesServer) error
	LocateMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
}

// UnimplementedDiscoveryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiscoveryServiceServer struct {
}

func (*UnimplementedDiscoveryServiceServer) StreamEndpoints(srv DiscoveryService_StreamEndpointsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEndpoints not implemented")
}
func (*UnimplementedDiscoveryServiceServer) StreamRoutes(srv DiscoveryService_StreamRoutesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRoutes not implemented")
}
func (*UnimplementedDiscoveryServiceServer) LocateMetrics(ctx context.Context, req *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LocateMetrics not implemented")
}

func RegisterDiscoveryServiceServer(s *grpc.Server, srv DiscoveryServiceServer) {
	s.RegisterService(&_DiscoveryService_serviceDesc, srv)
}

func _DiscoveryService_StreamEndpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DiscoveryServiceServer).StreamEndpoints(&discoveryServiceStreamEndpointsServer{stream})
}

type DiscoveryService_StreamEndpointsServer interface {
	Send(*EndpointResponse) error
	Recv() (*EndpointRequest, error)
	grpc.ServerStream
}

type discoveryServiceStreamEndpointsServer struct {
	grpc.ServerStream
}

func (x *discoveryServiceStreamEndpointsServer) Send(m *EndpointResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *discoveryServiceStreamEndpointsServer) Recv() (*EndpointRequest, error) {
	m := new(EndpointRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DiscoveryService_StreamRoutes_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DiscoveryServiceServer).StreamRoutes(&discoveryServiceStreamRoutesServer{stream})
}

type DiscoveryService_StreamRoutesServer interface {
	Send(*EndpointResponse) error
	Recv() (*EndpointRequest, error)
	grpc.ServerStream
}

type discoveryServiceStreamRoutesServer struct {
	grpc.ServerStream
}

func (x *discoveryServiceStreamRoutesServer) Send(m *EndpointResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *discoveryServiceStreamRoutesServer) Recv() (*EndpointRequest, error) {
	m := new(EndpointRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DiscoveryService_LocateMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).LocateMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DiscoveryService/LocateMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).LocateMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscoveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LocateMetrics",
			Handler:    _DiscoveryService_LocateMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEndpoints",
			Handler:       _DiscoveryService_StreamEndpoints_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamRoutes",
			Handler:       _DiscoveryService_StreamRoutes_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/api.proto",
}
