version: "3.7"
networks:
  servers:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"

services:
  watcher:
    container_name: watcher
    image: seankhliao/ndn-watcher
    expose:
      # watcher
      - "8000"
      # prometheus
      - "9090"
    networks:
      servers:
        ipv4_address: "172.20.0.2"

  primary1:
    container_name: primary1
    image: seankhliao/ndn-primary
    expose:
      # unicast
      - "6363"
      # primary
      - "8000"
    networks:
      servers:
        ipv4_address: "172.20.0.11"
    # volumes:
    #   - ./primary1/ndn:/usr/local/etc/ndn
    environment:
      WATCHER: "172.20.0.2:8000"
  server1:
    container_name: server1
    image: seankhliao/ndn-traffic
    expose:
      # unicast
      - "6363"
      # server
      - "8000"
    networks:
      servers:
        ipv4_address: "172.20.0.12"
    volumes:
      - ./server1/ndn:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_SERVER_DISABLED: ""
      PRIMARY: "172.20.0.11:8000"
      # NDN_AUTOCONFIG_DISABLED: ""
  # client1:
  #   container_name: client1
  #   image: seankhliao/ndn-traffic
  #   expose:
  #     # unicast
  #     - "6363"
  #     # server
  #     - "8000"
  #   networks:
  #     servers:
  #       ipv4_address: "172.20.0.12"
  #   volumes:
  #     - ./client1/ndn:/usr/local/etc/ndn
  #   environment:
  #     NDN_TRAFFIC_CLIENT_DISABLED: ""

  primary2:
    container_name: primary2
    image: seankhliao/ndn-primary
    expose:
      # unicast
      - "6363"
      # primary
      - "8000"
    networks:
      servers:
        ipv4_address: "172.20.0.21"
    # volumes:
    #   - ./primary2/ndn:/usr/local/etc/ndn
    environment:
      WATCHER: "172.20.0.2:8000"
  server2:
    container_name: server2
    image: seankhliao/ndn-traffic
    expose:
      # unicast
      - "6363"
      # server
      - "8000"
    networks:
      servers:
        ipv4_address: "172.20.0.22"
    volumes:
      - ./server2/ndn:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_SERVER_DISABLED: ""
      PRIMARY: "172.20.0.21:8000"
  # client2:
  #   container_name: client2
  #   image: seankhliao/ndn-traffic
  #   expose:
  #     # unicast
  #     - "6363"
  #     # server
  #     - "8000"
  #   networks:
  #     servers:
  #       ipv4_address: "172.20.0.12"
  #   volumes:
  #     - ./client2/ndn:/usr/local/etc/ndn
  #   environment:
  #     NDN_TRAFFIC_CLIENT_DISABLED: ""

  primary3:
    container_name: primary3
    image: seankhliao/ndn-primary
    expose:
      # unicast
      - "6363"
      # primary
      - "8000"
    networks:
      servers:
        ipv4_address: "172.20.0.31"
    # volumes:
    #   - ./primary3/ndn:/usr/local/etc/ndn
    environment:
      WATCHER: "172.20.0.2:8000"
  server3:
    container_name: server3
    image: seankhliao/ndn-traffic
    expose:
      # unicast
      - "6363"
      # server
      - "8000"
    networks:
      servers:
        ipv4_address: "172.20.0.32"
    volumes:
      - ./server3/ndn:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_SERVER_DISABLED: ""
      PRIMARY: "172.20.0.21:8000"
  # client3:
  #   container_name: client3
  #   image: seankhliao/ndn-traffic
  #   expose:
  #     # unicast
  #     - "6363"
  #     # server
  #     - "8000"
  #   networks:
  #     servers:
  #       ipv4_address: "172.20.0.12"
  #   volumes:
  #     - ./client3/ndn:/usr/local/etc/ndn
  #   environment:
  #     NDN_TRAFFIC_CLIENT_DISABLED: ""
