version: "3.7"
networks:
  servers:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
  clients:
    ipam:
      driver: default
      config:
        - subnet: "172.18.2.0/24"
services:
  prometheus:
    container_name: prometheus
    build: ./ndn-prometheus
    image: seankhliao/ndn-prometheus
    ports:
      # watcher
      - "8000"
      # prometheus
      - "9090"
    networks:
      servers:
        ipv4_address: "172.18.0.2"
  grafana:
    container_name: grafana
    build: ./ndn-grafana
    image: seankhliao/ndn-grafana
    ports:
      # grafana
      - "3000"
    networks:
      servers:
        ipv4_address: "172.18.0.3"
    depends_on:
      - prometheus

  server1:
    container_name: server1
    build: ./ndn-server
    image: seankhliao/ndn-server
    expose:
      # unicast
      - "6363"
      # multicast
      - "56363"
      # prometheus
      - "8000"
    networks:
      servers:
        ipv4_address: "172.18.0.11"
    volumes:
      - ./volumes/server1/ndn:/usr/local/etc/ndn
    depends_on:
      - prometheus
    # environment:
  server2:
    container_name: server2
    build: ./ndn-server
    image: seankhliao/ndn-server
    expose:
      # unicast
      - "6363"
      # multicast
      - "56363"
      # prometheus
      - "8000"
    networks:
      servers:
        ipv4_address: "172.18.0.12"
    volumes:
      - ./volumes/server2/ndn:/usr/local/etc/ndn
    depends_on:
      - prometheus
    # environment:

  router1:
    container_name: router1
    build: ./ndn-router
    image: seankhliao/ndn-router
    expose:
      # ndn-unicast
      - "6363"
      # ndn-multicast
      - "56363"
      # prometheus
      - "8000"
    networks:
      servers:
        ipv4_address: "172.18.0.21"
      clients:
        ipv4_address: "172.18.2.21"
    volumes:
      - ./volumes/router1/ndn:/usr/local/etc/ndn
    depends_on:
      - prometheus
    # environment:

  client1:
    container_name: client1
    build: ./ndn-client
    image: seankhliao/ndn-client
    networks:
      clients:
        ipv4_address: "172.18.2.31"
    volumes:
      - ./volumes/client1/ndn:/usr/local/etc/ndn
