version: "3.7"
networks:
  servers:
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"

services:
  watcher1:
    image: seankhliao/ndn-watcher
    expose:
      - "8000"
      - "9090"
    networks:
      servers:
        ipv4_address: "172.21.0.2"

  primary1:
    image: seankhliao/ndn-primary
    expose:
      - "6363"
      - "8000"
    networks:
      servers:
        ipv4_address: "172.21.1.1"
    environment:
      WATCHER: "172.21.0.2:8000"

  producer1a:
    image: seankhliao/ndn-traffic
    networks:
      servers:
        ipv4_address: "172.21.1.21"
    volumes:
      - ./producer1a:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_SERVER_DISABLED: ""

  consumer1a:
    image: seankhliao/ndn-traffic
    networks:
      servers:
        ipv4_address: "172.21.1.31"
    volumes:
      - ./consumer1a:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_CLIENT_DISABLED: ""
