version: "3.7"
networks:
  servers:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/16"

services:
  watcher1:
    image: seankhliao/ndn-watcher
    expose:
      - "8000"
      - "9090"
    networks:
      servers:
        ipv4_address: "172.23.0.2"

  primary1:
    image: seankhliao/ndn-primary
    expose:
      - "6363"
      - "8000"
    networks:
      servers:
        ipv4_address: "172.23.1.1"
    environment:
      WATCHER: "172.23.0.2:8000"

  secondary1a:
    image: seankhliao/ndn-secondary
    expose:
      - "6363"
      - "56363"
    networks:
      servers:
        ipv4_address: "172.23.1.11"
    environment:
      PRIMARY: "172.23.1.1:8000"
  secondary1b:
    image: seankhliao/ndn-secondary
    expose:
      - "6363"
      - "56363"
    networks:
      servers:
        ipv4_address: "172.23.1.12"
    environment:
      PRIMARY: "172.23.1.1:8000"

  producer1a:
    image: seankhliao/ndn-traffic
    networks:
      servers:
        ipv4_address: "172.23.1.21"
    volumes:
      - ./producer1a:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_SERVER_DISABLED: ""

  consumer1a:
    image: seankhliao/ndn-traffic
    networks:
      servers:
        ipv4_address: "172.23.1.31"
    volumes:
      - ./consumer1a:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_CLIENT_DISABLED: ""

  primary2:
    image: seankhliao/ndn-primary
    expose:
      - "6363"
      - "8000"
    networks:
      servers:
        ipv4_address: "172.23.2.1"
    environment:
      WATCHER: "172.23.0.2:8000"

  secondary2a:
    image: seankhliao/ndn-secondary
    expose:
      - "6363"
      - "56363"
    networks:
      servers:
        ipv4_address: "172.23.2.11"
    environment:
      PRIMARY: "172.23.2.1:8000"
  secondary2b:
    image: seankhliao/ndn-secondary
    expose:
      - "6363"
      - "56363"
    networks:
      servers:
        ipv4_address: "172.23.2.12"
    environment:
      PRIMARY: "172.23.2.1:8000"

  producer2a:
    image: seankhliao/ndn-traffic
    networks:
      servers:
        ipv4_address: "172.23.2.21"
    volumes:
      - ./producer2a:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_SERVER_DISABLED: ""

  consumer2a:
    image: seankhliao/ndn-traffic
    networks:
      servers:
        ipv4_address: "172.23.2.31"
    volumes:
      - ./consumer2a:/usr/local/etc/ndn
    environment:
      NDN_TRAFFIC_CLIENT_DISABLED: ""
