name: workflow
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/workflow.yaml
      - ndn-base/*
      - ndn-collector/*
      - ndn-server/*
      - ndn-sidecar/*
  schedule:
    - cron: "0 0 * * *"
jobs:
  # precache:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: docker pull seankhliao/ndn-base
  #     - run: docker pull seankhliao/ndn-collector
  #     - run: docker pull seankhliao/ndn-server
  #     - run: docker pull seankhliao/ndn-sidecar

  # ndn-base-cxx:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - precache
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: docker build -f ndn-base/Dockerfile.ndn-cxx -t ndn-cxx ndn-base
  # ndn-base-tools:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - precache
  #     - ndn-base-cxx
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: docker build -f ndn-base/Dockerfile.ndn-tools -t ndn-tools ndn-base
  # ndn-base-nfd:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - precache
  #     - ndn-base-cxx
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: docker build -f ndn-base/Dockerfile.ndn-nfd -t ndn-nfd ndn-base
  # ndn-base-nlsr:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - precache
  #     - ndn-base-nfd
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: docker build -f ndn-base/Dockerfile.ndn-nlsr -t ndn-nlsr ndn-base
  # ndn-base-traffic:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - precache
  #     - ndn-base-nfd
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: docker build -f ndn-base/Dockerfile.ndn-traffic -t ndn-traffic ndn-base
  # ndn-base:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - precache
  #     - ndn-base-cxx
  #     - ndn-base-tools
  #     - ndn-base-nfd
  #     - ndn-base-nlsr
  #     - ndn-base-traffic
  #   steps:
  #     - uses: actions/checkout@master
  #     - run: docker build -f ndn-base/Dockerfile.ndn-base -t docker.pkg.github.com/seankhliao/uva-rp1/ndn-base:latest -t seankhliao/ndn-base:latest ndn-base

  ndn-base:
    runs-on: ubuntu-latest
    # needs:
    #   - precache
    steps:
      - uses: actions/checkout@master
      - run: docker build -f ndn-base/Dockerfile -t docker.pkg.github.com/seankhliao/uva-rp1/ndn-base:latest -t seankhliao/ndn-base:latest ndn-base
      - run: docker login -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.DOCKERPAT }}
      - run: docker push seankhliao/ndn-base:latest
      - run: docker login docker.pkg.github.com -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUBPAT }}
      - run: docker push docker.pkg.github.com/seankhliao/uva-rp1/ndn-base:latest

  ndn-sidecar:
    runs-on: ubuntu-latest
    # needs:
    #   - precache
    steps:
      - uses: actions/checkout@master
      - run: docker build -f ndn-sidecar/Dockerfile -t docker.pkg.github.com/seankhliao/uva-rp1/ndn-sidecar:latest -t seankhliao/ndn-sidecar:latest ndn-sidecar
      - run: docker login -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.DOCKERPAT }}
      - run: docker push seankhliao/ndn-sidecar:latest
      - run: docker login docker.pkg.github.com -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUBPAT }}
      - run: docker push docker.pkg.github.com/seankhliao/uva-rp1/ndn-sidecar:latest

  ndn-collector:
    runs-on: ubuntu-latest
    # needs:
    #   - precache
    steps:
      - uses: actions/checkout@master
      - run: docker build -f ndn-collector/Dockerfile -t docker.pkg.github.com/seankhliao/uva-rp1/ndn-collector:latest -t seankhliao/ndn-collector:latest ndn-collector
      - run: docker login -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.DOCKERPAT }}
      - run: docker push seankhliao/ndn-collector:latest
      - run: docker login docker.pkg.github.com -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUBPAT }}
      - run: docker push docker.pkg.github.com/seankhliao/uva-rp1/ndn-collector:latest

  ndn-server:
    runs-on: ubuntu-latest
    needs:
      # - precache
      - ndn-base
      - ndn-sidecar
    steps:
      - uses: actions/checkout@master
      - run: docker build -f ndn-server/Dockerfile -t docker.pkg.github.com/seankhliao/uva-rp1/ndn-server:latest -t seankhliao/ndn-server:latest ndn-server
      - run: docker login -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.DOCKERPAT }}
      - run: docker push seankhliao/ndn-server:latest
      - run: docker login docker.pkg.github.com -u seankhliao -p $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUBPAT }}
      - run: docker push docker.pkg.github.com/seankhliao/uva-rp1/ndn-server:latest
